name: ${APP_NAME_HOST}

networks:
  internal:
    name: ${APP_NAME_HOST}_internal
    driver: bridge
    ipam:
      config:
        - subnet: "${APP_NETWORK_POOL}"

volumes:
  habitat-config:
  mosquitto-config:
  mosquitto-data:
  mosquitto-logs:

    # No Secrets, Syntax Stub:
    # secrets:
    #   SECRET_NAME:
    #     file: ${SECRETS_DIR}/SECRET_NAME


services:

  habitat-config-chatter:
    image: tschebbischeff/habitat-config:latest
    container_name: ${APP_NAME_HOST}_habitat-config-chatter
    restart: no
    env_file:
      - ./.env
      - path: ${ENV_DIR}/.env
        required: false
      - path: ${ENV_DIR}/habitat-config.env
        required: false
    environment:
      MODULE_NAME: "chatter"
    networks:
      internal:
    volumes:
      - habitat-config:/habitat-config/orchestration
      - ./habitat-config:/habitat-config/source:ro
      - mosquitto-config:/habitat-config/target/mosquitto

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: ${APP_NAME_HOST}_mosquitto
    restart: unless-stopped
    expose:
      - "1883"
      - "9001"
    env_file:
      - ./.env
      - path: ${ENV_DIR}/.env
        required: false
      - path: ${ENV_DIR}/mosquitto.env
        required: false
    volumes:
      - mosquitto-config:/mosquitto/config:ro
      - mosquitto-data:/mosquitto/data
      - mosquitto-logs:/mosquitto/log
    networks:
      internal:
    healthcheck:
      test: [ "CMD", "mosquitto_sub", "-V", "5", "-t", "$$SYS/#", "-C", "1", "-i", "healthcheck", "-W", "3" ] # Source: https://github.com/eclipse-mosquitto/mosquitto/issues/1270#issuecomment-1476038461
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s

  mqttx:
    image: emqx/mqttx-web:latest
    container_name: ${APP_NAME_HOST}_mqttx
    restart: unless-stopped
    expose:
      - "80"
    env_file:
      - ./.env
      - path: ${ENV_DIR}/.env
        required: false
      - path: ${ENV_DIR}/mqttx.env
        required: false
    networks:
      internal:
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://127.0.0.1:80" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
